conJob:
    admin:
        username: ${ADMIN_USERNAME:-}
        password: ${ADMIN_PASSWORD:-}
    auth:
        username: ${USERNAME:-}
        password: ${PASSWORD:-}

server:
    registerDefaultExceptionMappers: false
