---
container_name: conjob
image_name: scottg489/conjob:latest
adminUsername: "{{ lookup('env', '_ADMIN_USERNAME') }}"
adminPassword: "{{ lookup('env', '_ADMIN_PASSWORD') }}"
dockerUsername: "{{ lookup('env', '_DOCKER_USERNAME') }}"
dockerPassword: "{{ lookup('env', '_DOCKER_PASSWORD') }}"
