Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.hostname = "conjob-vm"

  config.vm.define "linux" do |lin|
    lin.vm.network "forwarded_port", guest: 80, host: 8080
    lin.vm.network "forwarded_port", guest: 8081, host: 8081

    lin.vm.provision "ansible" do |ansible|
      ansible.playbook = "master-playbook.yml"
    end
  end
end
